### ISSUE TITLE
What is the purpose of this wrapper app?

### ISSUE THREAD

**Issue by shalstein** [joeartsea/node-red-heroku#11]
Node-Red has already a built-in means of adjusting settings.js such that flows will be password protected. Does this app provide an additional layer of security on top of that?

**Comment by joeartsea** [comment]
No, I'm using Node-RED standard authentication system. 
https://github.com/joeartsea/node-red-heroku/blob/master/settings.js#L59-L78

This wrapper app is purpose is possible to execute the Node-RED in Heroku. To do that, need to use the data store. It has customized it.
https://github.com/joeartsea/node-red-heroku/blob/master/mongostorage.js
