### ISSUE TITLE
Flows

### ISSUE THREAD

**Issue by Digital-Thor** [joeartsea/node-red-heroku#13]
Hello Atsushi. Thanks for this Heroku button!  It made it a lot easier to move my local NR implementation to Heroku.  

One question though -- I followed [the readme instructions](https://github.com/joeartsea/node-red-heroku/blob/master/defaults/README.md), but found that moving my local flow files into the `defaults` folder didn't work.  I had to export/import using the clipboard, but not sure where the new flow files are in Heroku.  Any suggestions?  -Thor

**Comment by joeartsea** [comment]
It uses MongoDB as storage. It can be confirmed with the resources of Heroku dashboard.
https://github.com/joeartsea/node-red-heroku/blob/master/mongostorage.js

**Comment by Digital-Thor** [comment]
Thank you. Yes, I found it in my Mongo Dashboard > "nodered" collection.
