### ISSUE TITLE
mLab MongoDB add-on for Heroku discontinued

### ISSUE THREAD

**Issue by carlosortegatoro** [joeartsea/node-red-heroku#17]
Is there any plan to change the storage from mLab MongoDB to Postgre SQL or something supported by Heroku?

**Comment by joeartsea** [comment]
The mLab add-on will be unavailable in November, so we'll have to change the storage, but we haven't decided on a specific alternative yet.

**Comment by joeartsea** [comment]
Changed storage from MongoDB to Postgres SQL.
