### ISSUE TITLE
Update node-red version ?

### ISSUE THREAD

**Issue by aessig** [joeartsea/node-red-heroku#20]
Hello, 

Thank you for this repo. It's super useful. 
I have deployed an instance a year ago and I'm wondering how one should update the version of node-red without re-deploying. 

Please let me know, 

Best regards,

**Comment by joeartsea** [comment]
The following is helpful.
https://stackoverflow.com/questions/28737548/how-to-update-an-heroku-app-created-using-github-deploy-to-heroku-button
