### ISSUE TITLE
Node-RED apps suddenly crashing last 7 days - no pg_hba.conf host entry?

### ISSUE THREAD

**Issue by aMacDawg** [joeartsea/node-red-heroku#21]
Hi there, I have been using this Heroku element with no issues for the last 4 months. However, all 4x of my Node-RED Heroku apps have been crashing upon startup within the last 7 days. 

Looking at the logs shows this:

```
2021-03-16T05:40:15.998255+00:00 heroku[web.1]: Starting process with command `node --max-old-space-size=384 node_modules/node-red/red.js --settings ./settings.js`
2021-03-16T05:40:19.832866+00:00 app[web.1]: pgUrl postgres://<redacted>
2021-03-16T05:40:19.834452+00:00 app[web.1]: create pg tables
2021-03-16T05:40:20.241122+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: error: no pg_hba.conf entry for host "<redacted>", user "<redacted>", database "<redacted>", SSL off
//truncated...
2021-03-16T05:40:20.302015+00:00 app[web.1]: TIMEOUT:  getSettings
2021-03-16T05:40:20.397532+00:00 heroku[web.1]: Process exited with status 0
2021-03-16T05:40:20.565037+00:00 heroku[web.1]: State changed from starting to crashed
```

This behavior is repeatable across all 4 of my Node-RED heroku apps any time I attempt to restart the dynos.

From what I can tell, it seems there's the `getSettings` function in `pgstorage.js` is experiencing timeout and that's now causing the app to crash.

I haven't made any modifications or forked this repo, is there some larger change you're aware of or suggested approach to resolve?

**Comment by e-labInnovations** [comment]
Hi 
Can you find this kind of notification on your heroku dashboard (notification section)
 
-------


- **Action Required] - Your app(s) using free dyno hours have stopped running** 

You have used your entire allocation of 550 free dyno hours for March 2021.

**Your app(s) have stopped running and will not restart until you receive more free dyno hours next month.** 

To keep your app(s) running smoothly, consider [upgrading to Hobby dynos](https://hello.heroku.com/appsdash) for $7 per dyno per month. Your app(s) will stay live and your users will enjoy 24/7 access.

**Comment by aMacDawg** [comment]
thanks @e-labInnovations for the comment. two of the Node-RED apps are actually already running on paid dynos (paid Hobby) although the postgres dynos are running on the free _hobby dev_  dynos and the Heroku dashboard had not displayed any notifications.

Nonetheless, I tried upgrading the _hobby dev_ postgres dynos to the paid version just to check and found that upgrading to the $9 had no impact on the issue.

**Comment by e-labInnovations** [comment]
Sorry @aMacDawg
I have the same problem. But saw that notification.

**Comment by joeartsea** [comment]
@aMacDawg 
I changed the SSL connection to postgres and it worked. 
I don't know why it was working without SSL connection before.

**Comment by e-labInnovations** [comment]
@joeartsea 
How to change it?
On environmental variable (heroku app **Config vars** )?

Please explain

**Comment by joeartsea** [comment]
@e-labInnovations
See the commit log referenced in my comment.
https://github.com/joeartsea/node-red-heroku/commit/515cd2ef72780680d6d3c37f6306aec68b8cb62a

You can either create a new app with heroku button and import flow etc. or change the source code of your own existing app to the above.

**Comment by aMacDawg** [comment]
hi @joeartsea thanks again for your help and the speedy commit fix. I cloned the repo and was able to resolve the issue.

Out of curiosity, would there be a way to recover the flow definitions stored in the heroku apps where I am unable to change the `pgutils` codefile with the update key-value pair?

I tried connecting to the postgres database in the past but all the tables I queried were empty and I didn't see any table specifically created for storing the node-red flows

**Comment by joeartsea** [comment]
@aMacDawg 
Flow definitions are stored in postgres.
If you can’t run Node-RED, you'll have to connect directly to Postgres and retrieve the flow definitions.

**Comment by aMacDawg** [comment]
thanks @joeartsea , would you have any more detail on _where_ in my heroku postgres I should be querying? I tried the query `\dt` to list all the tables and I only saw `eConfigs`, `eLibs`, and `ePrivateNodes` all of which returned 0 rows.

(running the query `SELECT * FROM "eConfigs";` listed the `id | appname` columns without displaying any records)

I wonder if I am not looking in the right schema?

I am connecting with the `heroku psql --app <my-app-name>` command

**Comment by joeartsea** [comment]
@aMacDawg 
I don't know why your table has 0 rows, but when I connect to heroku postgre where my flow exists with Postico (https://eggerapps.at/postico/), I get the following.

I see three tables, so I choose "eConfigs".
<img width="951" alt="Screen Shot 2021-03-18 at 22 56 53" src="https://user-images.githubusercontent.com/94586/111639033-3ac0dd00-883e-11eb-9fdf-efe2f00f63be.png">

The table data is displayed and you can see the flow data in the "flows" column.
<img width="948" alt="Screen Shot 2021-03-18 at 22 57 04" src="https://user-images.githubusercontent.com/94586/111639056-3e546400-883e-11eb-82a3-00fddba62224.png">

**Comment by aMacDawg** [comment]
hey @joeartsea thanks for the walkthrough and the screenshots. I am trying to connect to the heroku postgres using the credentials provided in the Postgres's admin panel in the dashboard, however when I try to connect I get the same error:

```
no pg_hba.conf entry for host "<redacted>", user "<redacted>", database "<redacted>", SSL off
```

Did you connect to the heorku postgres using an SSH or SSL connection?

_Edit_: I actually found a way to get in using this [YouTube video](https://www.youtube.com/watch?v=P0MvXvBTklQ) to guide me and I see some flow data there!

Thanks for the tip

**Comment by joeartsea** [comment]
@aMacDawg 
Yes, the client I used, Postico, always seems to connect over SSL.
You can find it at https://eggerapps.at/postico/docs/v1.0.5/security.html

**Comment by e-labInnovations** [comment]
@joeartsea 
Please help me
I used ` digitaloak/node-red-contrib-digitaloak-postgresql ` for using heroku postgresql. But now it is also fail to connect. There is a option to use SSL. But I don't know to use it. Please help me :pensive:
