### ISSUE TITLE
Couldn't install custom nodes via manage palette

### ISSUE THREAD

**Issue by Yasirunet** [joeartsea/node-red-heroku#23]
I used the deploy to Heroku button to deploy the node-red instance to Heroku and the deployment was successful. But I couldn't add custom nodes via manage palette. Following I attached a snapshot of the package installing log. Seems something is wrong with the node and npm versions.

![image](https://user-images.githubusercontent.com/15893083/167382953-5f5b17fc-9f16-4e66-ab05-8676d44d452f.png)

**System info** 
Node-red version: 2.2.2: Maintenance Release
hroku-buildpack: heroku/nodejs

**Comment by ptath** [comment]
same problem
